""" tests ModelFit - software to fit regression models using count data - software to do store PCA output.
    Only tests this with 
"""
import unittest
import os
import datetime
import pickle
import glob
from pca.fittrend import ModelCounts


class Test_Fit_1(unittest.TestCase):
    """tests fitting of models"""

    def runTest(self):

        # read cntdata, which has been generated by PCADatabaseManager.pcas_count_table()
        # see unit test Test_PCADB_3 for example.

        srcdir = os.path.join("testdata", "modelfit")
        globpath = os.path.join(srcdir, "*.pickle")
        for picklefile in glob.glob(globpath):
            with open(picklefile, "rb") as f:
                cntdata = pickle.load(f)

            analysis_date = datetime.date.fromisoformat("2022-01-01")
            analysis_start = analysis_date - datetime.timedelta(days=30)
            pc_cat = cntdata["pc_cat"]

            mc = ModelCounts(
                counts=cntdata["counts"],
                denominators=cntdata["denominators"],
                pcas_int_id=1,
                pc_cat=pc_cat,
                earliest_date=analysis_start,
                latest_date=analysis_date,
            )

            pf = mc.fit_poisson()
            nbf = mc.fit_nb()

            # no checks done on output at present
            print(pf)
            print(nbf)
