# This workflow will build the latest version of nim
# and test catwalk

name: Test catwalk with latest nim

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test catwalk with latest nim'
  push:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nim 
      run: |
        mkdir external_software
        cd external_software
        wget https://nim-lang.org/download/nim-1.4.8-linux_x64.tar.xz
        tar -xf nim-1.4.8-linux_x64.tar.xz

        echo "Checking nimble works when relative path applied"
        ./nim-1.4.8/bin/nimble --version

        # show what is on the path
        echo "Current path"
        sed 's/:/\n/g' <<< "$PATH"

        NIMDIR="`pwd`/nim-1.4.8/bin"
        echo "Nim directory:"
        echo "$NIMDIR"

        echo "Checking nimble works when computed NIMDIR path applied"
        ${NIMDIR}/nimble --version

        echo "Appending to PATH"
        echo "$NIMDIR" >> $GITHUB_PATH


    - name: compile catwalk
      run: |
        echo "Updated path"       
        # show what is on the path
        sed 's/:/\n/g' <<< "$PATH"

        # is nimble accessible on path
        echo "Nimble version:"
        nimble --version

