# This workflow will build the latest version of nim
# and test catwalk

name: Test catwalk with latest nim

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test catwalk with latest nim'
  push:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        mongodb-version: ["4.4.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nim environment and catwalk
      run: |
        mkdir external_software
        cd external_software
        wget https://nim-lang.org/download/nim-1.4.8-linux_x64.tar.xz
        tar -xf nim-1.4.8-linux_x64.tar.xz

        echo "Checking nimble works when absolute path applied"
        ./nim-1.4.8/bin/nimble --version

        # show what is on the path
        echo "Current path"
        sed 's/:/\n/g' <<< "$PATH"

        NIMDIR="`pwd`/nim-1.4.8/bin"
        echo "Nim directory:"
        echo "$NIMDIR"

        echo "Checking nimble works when computed NIMDIR path applied"
        ${NIMDIR}/nimble --version

        echo "Appending to PATH"
        echo "{NIMDIR}" >> $GITHUB_PATH

        echo "Updated path"       
        # show what is on the path
        sed 's/:/\n/g' <<< "$PATH"

        # is nimble accessible on path
        echo "Nimble version:"
        nimble --version

        # clone catwalk relatedness engine
        git clone https://gitea.mmmoxford.uk/dvolk/catwalk.git
        cd catwalk

        echo "Compiling with nimble"
        nimble -y build -d:release -d:danger -d:no_serialisation 

        # add path to executable to .env file 
        echo CW_BINARY_FILEPATH=\"`pwd`/cw_server\" > ../../.env
        # back to original directory
        cd ../..
