# This workflow will build the latest version of nim
# and test catwalk

name: Test catwalk with latest nim

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test catwalk with latest nim'
  push:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nim 
      run: |

        mkdir external_software
        cd external_software
        ls
        wget https://nim-lang.org/download/nim-1.4.8-linux_x64.tar.xz
        tar -xf nim-1.4.8-linux_x64.tar.xz

        NIMDIR="`pwd`/nim-1.4.8/bin"

        # Appending to PATH
        echo "$NIMDIR" >> $GITHUB_PATH

    - name: check nimble is available
      run: |
        # check nimble is accessible on path
        echo "Nimble version:"
        nimble --version

    - name: clone catwalk
      run: |
        # clone catwalk relatedness engine
        cd external_software
        ls
        git clone https://gitea.mmmoxford.uk/dvolk/catwalk.git catwalk
        
    - name: compile catwalk
      run: |
        cd external_software/catwalk
        nimble -y build -d:release -d:danger -d:no_serialisation
        echo CW_BINARY_FILEPATH=\"`pwd`/cw_server\" > ../../.env
      
