# This workflow will build the latest version of nim
# and test catwalk

name: Test catwalk with latest nim

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test catwalk with latest nim'
  push:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        mongodb-version: [4.4.4]

    steps:
    - name: Setup Nim environment
    - uses: jiro4989/setup-nim-action@v1.1.4

