# This workflow will build the latest version of nim
# and test catwalk

name: Test catwalk with latest nim

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test catwalk with latest nim'
  push:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        mongodb-version: ["4.4.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nim environment
      run: |
        mkdir external_software
        cd external_software
        wget https://nim-lang.org/download/nim-1.4.8-linux_x64.tar.xz
        tar -xf nim-1.4.8-linux_x64.tar.xz
        ./nim-1.4.8/bin/nimble --version
